import { describe, it, expect } from "vitest";
import type { Invoice, TimeEntry } from "@job-tracker/shared";
import { splitByBilling } from "./billing";

function entry(id: number, startedAt: string, durationMin: number | null): TimeEntry {
  return {
    id,
    projectId: 1,
    taskId: null,
    startedAt,
    endedAt: null,
    durationMin,
    notes: null,
    createdAt: startedAt,
    updatedAt: startedAt,
  };
}

function invoice(id: number, issuedDate: string, timeEntryIds: number[]): Invoice {
  return {
    id,
    projectId: 1,
    invoiceNumber: `INV-${id}`,
    status: "sent",
    issuedDate,
    dueDate: null,
    periodStart: null,
    periodEnd: null,
    subtotal: "0",
    taxRate: "0",
    taxAmount: "0",
    total: "0",
    notes: null,
    autoGenerated: false,
    viewedAt: null,
    createdAt: issuedDate,
    updatedAt: issuedDate,
    timeEntryIds,
  };
}

describe("splitByBilling", () => {
  it("counts an entry older than the last invoice as unbilled when no invoice claims it", () => {
    // The regression: the total used to filter on startedAt > issuedDate, so
    // this entry was listed as unbilled but excluded from the hours shown.
    const entries = [entry(1, "2026-08-04T09:00:00Z", 120)];
    const invoices = [invoice(10, "2026-08-06", [])];

    const { unbilled, unbilledHours } = splitByBilling(entries, invoices);

    expect(unbilled.map((e) => e.id)).toEqual([1]);
    expect(unbilledHours).toBe(2);
  });

  it("excludes entries an invoice claims and maps them to that invoice", () => {
    const entries = [
      entry(1, "2026-08-01T09:00:00Z", 60),
      entry(2, "2026-08-02T09:00:00Z", 90),
    ];
    const invoices = [invoice(10, "2026-08-03", [1])];

    const { unbilled, billed, entryInvoices, unbilledHours } = splitByBilling(entries, invoices);

    expect(billed.map((e) => e.id)).toEqual([1]);
    expect(unbilled.map((e) => e.id)).toEqual([2]);
    expect(entryInvoices.get(1)?.id).toBe(10);
    expect(unbilledHours).toBe(1.5);
  });

  it("treats a null duration as zero hours", () => {
    const { unbilledHours } = splitByBilling([entry(1, "2026-08-01T09:00:00Z", null)], []);
    expect(unbilledHours).toBe(0);
  });

  it("returns every entry as unbilled when there are no invoices", () => {
    const entries = [entry(1, "2026-08-01T09:00:00Z", 30), entry(2, "2026-08-02T09:00:00Z", 30)];

    const { unbilled, billed, unbilledHours } = splitByBilling(entries, []);

    expect(unbilled).toHaveLength(2);
    expect(billed).toHaveLength(0);
    expect(unbilledHours).toBe(1);
  });
});
