import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import type { Invoice, Profile, Project } from "@job-tracker/shared";
import { invoicesApi } from "../api/invoices";
import { profileApi } from "../api/profile";
import { projectsApi } from "../api/projects";
import { Badge } from "../components/ui/Badge";
import { Button } from "../components/ui/Button";
import { Select } from "../components/ui/Input";
import styles from "./InvoiceDetailPage.module.css";

function formatHours(quantity: string): string {
  const n = parseFloat(quantity);
  return String(n);
}

function formatAddress(p: Profile): string[] {
  const lines: string[] = [];
  if (p.street) lines.push(p.street);
  const cityLine = [p.city, p.state].filter(Boolean).join(", ");
  const withZip = [cityLine, p.zip].filter(Boolean).join(" ");
  if (withZip) lines.push(withZip);
  return lines;
}

export function InvoiceDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const invoiceId = parseInt(id!, 10);
  const [invoice, setInvoice] = useState<Invoice | null>(null);
  const [profile, setProfile] = useState<Profile | null>(null);
  const [project, setProject] = useState<Project | null>(null);

  useEffect(() => {
    invoicesApi.get(invoiceId).then((inv) => {
      setInvoice(inv);
      projectsApi.get(inv.projectId).then(setProject).catch(console.error);
      if (inv.autoGenerated && !inv.viewedAt) {
        invoicesApi
          .update(invoiceId, { viewedAt: new Date().toISOString() })
          .then((updated) => setInvoice((prev) => ({ ...updated, lineItems: prev?.lineItems })))
          .catch(console.error);
      }
    }).catch(console.error);
    profileApi.get().then(setProfile).catch(console.error);
  }, [invoiceId]);

  const handleStatusChange = async (status: string) => {
    const updated = await invoicesApi.update(invoiceId, { status: status as Invoice["status"] });
    setInvoice((prev) => ({ ...updated, lineItems: prev?.lineItems }));
  };

  if (!invoice) return <p>Loading...</p>;

  const rate = invoice.lineItems?.[0]?.unitPrice;
  const addressLines = profile ? formatAddress(profile) : [];
  const totalHours = (invoice.lineItems ?? []).reduce(
    (sum, item) => sum + parseFloat(item.quantity),
    0,
  );

  const handlePrint = () => {
    const companyName = profile?.businessName || profile?.yourName || "";
    const parts = [companyName, invoice.invoiceNumber].filter(Boolean);
    const originalTitle = document.title;
    document.title = parts.join(" ");
    window.print();
    document.title = originalTitle;
  };

  return (
    <div className={styles.page}>
      <div className={styles.actions}>
        <button className={styles.back} onClick={() => navigate("/invoices")}>
          ← Invoices
        </button>
        <div className={styles.actionBtns}>
          <Select
            label=""
            value={invoice.status}
            onChange={(e) => handleStatusChange(e.target.value)}
          >
            <option value="draft">Draft</option>
            <option value="sent">Sent</option>
            <option value="paid">Paid</option>
          </Select>
          <Button variant="secondary" onClick={handlePrint}>
            Print / PDF
          </Button>
        </div>
      </div>

      <div className={styles.invoice}>
        <div className={styles.invoiceHeader}>
          <div className={styles.sender}>
            {profile?.businessName && <strong>{profile.businessName}</strong>}
            {!profile?.businessName && profile?.yourName && <strong>{profile.yourName}</strong>}
            {addressLines.map((line, i) => <span key={i}>{line}</span>)}
            {profile?.email && <span>{profile.email}</span>}
            {profile?.phone && <span>{profile.phone}</span>}
          </div>
          <div className={styles.invoiceMeta}>
            <div className={styles.invoiceTitle}>
              <h1 className={styles.invoiceNumber}>{invoice.invoiceNumber}</h1>
              <Badge value={invoice.status} />
            </div>
            <div className={styles.dates}>
              <div>
                <span className={styles.dateLabel}>Issued</span>
                <span>{invoice.issuedDate}</span>
              </div>
              {invoice.dueDate && (
                <div>
                  <span className={styles.dateLabel}>Due</span>
                  <span>{invoice.dueDate}</span>
                </div>
              )}
            </div>
          </div>
        </div>

        {project && (
          <div className={styles.billTo}>
            <span className={styles.billToLabel}>Bill To</span>
            <strong>{project.clientName}</strong>
          </div>
        )}

        <div className={styles.tableHeader}>
          {rate && (
            <span className={styles.rateNote}>
              Rate: ${parseFloat(rate).toFixed(2)}/hr
            </span>
          )}
        </div>

        <table className={styles.lineItems}>
          <thead>
            <tr>
              <th>Date</th>
              <th>Task</th>
              <th className={styles.right}>Hours</th>
              <th className={styles.right}>Amount</th>
            </tr>
          </thead>
          <tbody>
            {(invoice.lineItems ?? []).map((item) => (
              <tr key={item.id}>
                <td>
                  {item.date
                    ? new Date(item.date + "T00:00:00").toLocaleDateString()
                    : "—"}
                </td>
                <td>{item.tasks || item.description || "—"}</td>
                <td className={styles.right}>{formatHours(item.quantity)}</td>
                <td className={styles.right}>
                  ${parseFloat(item.amount).toFixed(2)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className={styles.totals}>
          <div className={styles.totalRow}>
            <span>Subtotal ({totalHours} hrs)</span>
            <span>${parseFloat(invoice.subtotal).toFixed(2)}</span>
          </div>
          {parseFloat(invoice.taxRate) > 0 && (
            <div className={styles.totalRow}>
              <span>Tax ({(parseFloat(invoice.taxRate) * 100).toFixed(2)}%)</span>
              <span>${parseFloat(invoice.taxAmount).toFixed(2)}</span>
            </div>
          )}
          <div className={`${styles.totalRow} ${styles.grandTotal}`}>
            <span>Total</span>
            <span>${parseFloat(invoice.total).toFixed(2)}</span>
          </div>
        </div>

        {invoice.notes && <p className={styles.notes}>{invoice.notes}</p>}
      </div>
    </div>
  );
}
