import { db } from "../db/client";
import {
  invoices,
  invoiceLineItems,
  invoiceTimeEntries,
  timeEntries,
  timeEntryTasks,
  tasks,
  projects,
} from "../db/schema/index";
import { eq, and, gte, lte, like } from "drizzle-orm";
import { groupTimeEntriesByDay, nextInvoiceNumber } from "./invoice-helpers";

export interface GenerateInvoiceOptions {
  issuedDate: string;
  dueDate: string | null;
  taxRate: string;
  notes: string | null;
  autoGenerated: boolean;
}

export async function generateInvoiceForPeriod(
  projectId: number,
  periodStart: string | null,
  periodEnd: string | null,
  opts: GenerateInvoiceOptions
) {
  const project = await db.query.projects.findFirst({
    where: eq(projects.id, projectId),
  });
  if (!project) throw new Error("Project not found");

  // Query time entries in period, filtering by startedAt
  const entryConditions = [eq(timeEntries.projectId, projectId)];
  if (periodStart)
    entryConditions.push(gte(timeEntries.startedAt, new Date(periodStart)));
  if (periodEnd)
    entryConditions.push(lte(timeEntries.startedAt, new Date(periodEnd + "T23:59:59.999Z")));

  const entries = await db.query.timeEntries.findMany({
    where: and(...entryConditions),
  });

  // Fetch task titles for each entry
  const entriesWithTasks = await Promise.all(
    entries.map(async (entry) => {
      const entryTasks = await db
        .select({ title: tasks.title })
        .from(timeEntryTasks)
        .innerJoin(tasks, eq(timeEntryTasks.taskId, tasks.id))
        .where(eq(timeEntryTasks.timeEntryId, entry.id));
      return {
        startedAt: entry.startedAt ? entry.startedAt.toISOString() : null,
        durationMin: entry.durationMin,
        notes: entry.notes,
        taskTitles: entryTasks.map((t) => t.title),
      };
    })
  );

  // Group entries by calendar day
  const dayGroups = groupTimeEntriesByDay(entriesWithTasks);

  // Generate invoice number: INV-YYYY-NNN, scoped to the current year and
  // based on the highest existing sequence number (not the count), so gaps
  // or out-of-order existing numbers don't cause collisions.
  const year = new Date().getFullYear();
  const existingForYear = await db.query.invoices.findMany({
    where: like(invoices.invoiceNumber, `INV-${year}-%`),
    columns: { invoiceNumber: true },
  });
  const invoiceNumber = nextInvoiceNumber(
    existingForYear.map((inv) => inv.invoiceNumber),
    year
  );

  // Build line items from day groups
  const rate = parseFloat(project.rate);
  let subtotal = 0;
  const lineItemsData = dayGroups.map((group) => {
    const hours = group.totalMinutes / 60;
    const quantity = hours.toFixed(2);
    const amount = (hours * rate).toFixed(2);
    subtotal += hours * rate;
    return {
      date: group.date,
      tasks: group.tasks || null,
      description: group.description || `Work on ${project.name}`,
      quantity,
      unitPrice: project.rate,
      amount,
    };
  });

  const taxRateNum = parseFloat(opts.taxRate);
  const taxAmount = (subtotal * taxRateNum).toFixed(2);
  const total = (subtotal + parseFloat(taxAmount)).toFixed(2);

  // Create invoice + line items in a transaction
  return db.transaction(async (tx) => {
    const [invoice] = await tx
      .insert(invoices)
      .values({
        projectId,
        invoiceNumber,
        issuedDate: opts.issuedDate,
        dueDate: opts.dueDate,
        periodStart,
        periodEnd,
        subtotal: subtotal.toFixed(2),
        taxRate: opts.taxRate,
        taxAmount,
        total,
        notes: opts.notes,
        autoGenerated: opts.autoGenerated,
      })
      .returning();

    const items =
      lineItemsData.length > 0
        ? await tx
            .insert(invoiceLineItems)
            .values(
              lineItemsData.map((li) => ({ ...li, invoiceId: invoice.id }))
            )
            .returning()
        : [];

    if (entries.length > 0) {
      await tx.insert(invoiceTimeEntries).values(
        entries.map((e) => ({ invoiceId: invoice.id, timeEntryId: e.id }))
      );
    }

    return { ...invoice, lineItems: items };
  });
}
