import { Hono } from "hono";
import { db } from "../db/client";
import { invoices, invoiceLineItems, projects, profile } from "../db/schema/index";
import { eq, and } from "drizzle-orm";
import { parseId, rowOrNotFound } from "../utils/route-helpers";
import { generateInvoiceForPeriod } from "../lib/generate-invoice";
import { getMostRecentCompletedPeriod } from "../lib/invoice-helpers";

export const invoicesRouter = new Hono();

invoicesRouter.get("/", async (c) => {
  const projectId = c.req.query("projectId");
  const status = c.req.query("status") as
    | "draft"
    | "sent"
    | "paid"
    | undefined;

  const conditions = [];
  if (projectId)
    conditions.push(eq(invoices.projectId, parseInt(projectId, 10)));
  if (status) conditions.push(eq(invoices.status, status));

  const rows = await db.query.invoices.findMany({
    where: conditions.length > 0 ? and(...conditions) : undefined,
    orderBy: (inv, { desc }) => [desc(inv.createdAt)],
  });
  return c.json(rows);
});

invoicesRouter.post("/", async (c) => {
  const body = await c.req.json();
  const {
    projectId,
    issuedDate,
    dueDate,
    periodStart,
    periodEnd,
    taxRate = "0",
    notes,
  } = body;

  const project = await db.query.projects.findFirst({
    where: eq(projects.id, projectId),
  });
  if (!project) return c.json({ error: "Project not found" }, 404);

  const result = await generateInvoiceForPeriod(
    projectId,
    periodStart ?? null,
    periodEnd ?? null,
    {
      issuedDate,
      dueDate: dueDate ?? null,
      taxRate,
      notes: notes ?? null,
      autoGenerated: false,
    }
  );

  return c.json(result, 201);
});

invoicesRouter.post("/auto-draft", async (c) => {
  const today = new Date().toISOString().slice(0, 10);

  const activeProjects = await db.query.projects.findMany({
    where: and(eq(projects.status, "active"), eq(projects.autoInvoiceEnabled, true)),
  });

  const profileRow = await db.query.profile.findFirst();

  const created = [];
  for (const project of activeProjects) {
    try {
      const period = getMostRecentCompletedPeriod(
        project.startDate,
        project.autoInvoiceFrequencyDays,
        today
      );
      if (!period) continue;

      const existingInvoice = await db.query.invoices.findFirst({
        where: and(
          eq(invoices.projectId, project.id),
          eq(invoices.periodStart, period.periodStart),
          eq(invoices.periodEnd, period.periodEnd)
        ),
      });
      if (existingInvoice) continue;

      const invoice = await generateInvoiceForPeriod(
        project.id,
        period.periodStart,
        period.periodEnd,
        {
          issuedDate: today,
          dueDate: null,
          taxRate: profileRow?.defaultTaxRate ?? "0",
          notes: null,
          autoGenerated: true,
        }
      );
      created.push(invoice);
    } catch (err) {
      console.error(`Auto-draft failed for project ${project.id}:`, err);
    }
  }

  return c.json(created, 201);
});

invoicesRouter.get("/:id", async (c) => {
  const id = parseId(c);
  const row = await db.query.invoices.findFirst({
    where: eq(invoices.id, id),
    with: { lineItems: true },
  });
  return rowOrNotFound(c, row);
});

invoicesRouter.patch("/:id", async (c) => {
  const id = parseId(c);
  const body = await c.req.json();
  const [row] = await db
    .update(invoices)
    .set({ ...body, updatedAt: new Date() })
    .where(eq(invoices.id, id))
    .returning();
  return rowOrNotFound(c, row);
});

invoicesRouter.delete("/:id", async (c) => {
  const id = parseId(c);
  const inv = await db.query.invoices.findFirst({ where: eq(invoices.id, id) });
  if (!inv) return c.json({ error: "Not found" }, 404);
  if (inv.status !== "draft")
    return c.json({ error: "Can only delete draft invoices" }, 400);
  await db.delete(invoices).where(eq(invoices.id, id));
  return c.json({ success: true });
});

// Line item management
invoicesRouter.post("/:id/line-items", async (c) => {
  const invoiceId = parseId(c);
  const body = await c.req.json();
  const [row] = await db
    .insert(invoiceLineItems)
    .values({ ...body, invoiceId })
    .returning();
  return c.json(row, 201);
});

invoicesRouter.patch("/:id/line-items/:itemId", async (c) => {
  const itemId = parseInt(c.req.param("itemId"), 10);
  const body = await c.req.json();
  const [row] = await db
    .update(invoiceLineItems)
    .set(body)
    .where(eq(invoiceLineItems.id, itemId))
    .returning();
  return rowOrNotFound(c, row);
});

invoicesRouter.delete("/:id/line-items/:itemId", async (c) => {
  const itemId = parseInt(c.req.param("itemId"), 10);
  const [row] = await db
    .delete(invoiceLineItems)
    .where(eq(invoiceLineItems.id, itemId))
    .returning();
  if (!row) return c.json({ error: "Not found" }, 404);
  return c.json({ success: true });
});
